# Generated by Django 3.2.6 on 2021-11-23 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=20)),
                ('current_address', models.CharField(max_length=500)),
                ('profile_pic', models.ImageField(null=True, upload_to='images')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedSightApp.users', to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('prefix', models.CharField(max_length=5)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=20)),
                ('current_address', models.CharField(max_length=500)),
                ('specialization', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(null=True, upload_to='images')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedSightApp.users', to_field='username')),
            ],
        ),
    ]
