# Generated by Django 3.2.6 on 2021-11-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedSightApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='experience',
            field=models.CharField(default=5, max_length=5),
            preserve_default=False,
        ),
    ]
