# Generated by Django 3.2.6 on 2021-11-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedSightApp', '0003_auto_20211113_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.CharField(default='active', max_length=15),
        ),
    ]
