# Generated by Django 3.2.6 on 2021-11-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedSightApp', '0004_users_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='med_license',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='patients',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
