# Generated by Django 3.2.6 on 2021-11-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedSightApp', '0005_appointments_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='apt_reason',
            field=models.CharField(default='Fever', max_length=30),
            preserve_default=False,
        ),
    ]
