# Generated by Django 3.2.6 on 2021-11-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedSightApp', '0005_auto_20211116_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='status',
        ),
        migrations.AlterField(
            model_name='doctors',
            name='med_license',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='images//'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
