# Generated by Django 3.2.6 on 2021-11-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedSightApp', '0006_appointments_apt_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
