# Generated by Django 3.2.6 on 2021-11-16 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedSightApp', '0008_auto_20211116_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='med_license',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='profile_pic',
        ),
    ]
