# Generated by Django 3.2.6 on 2021-12-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedSightApp', '0009_auto_20211130_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='rating_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
