# Generated by Django 3.2.6 on 2021-11-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedSightApp', '0009_auto_20211116_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='upload/'),
        ),
    ]
