# Generated by Django 3.2.6 on 2021-12-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedSightApp', '0010_ratings_rating_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='rate_time',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
