# Generated by Django 3.2.6 on 2021-11-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedSightApp', '0010_doctors_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='specialization',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctors',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
