# Generated by Django 3.2.6 on 2021-11-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedSightApp', '0011_auto_20211119_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='gender',
            field=models.CharField(default='Dr.', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctors',
            name='prefix',
            field=models.CharField(default='Dr.', max_length=5),
            preserve_default=False,
        ),
    ]
