# Generated by Django 3.2.6 on 2021-11-22 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MedSightApp', '0012_auto_20211119_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='gender',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patients',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
