# Generated by Django 3.2.6 on 2021-11-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedSightApp', '0016_auto_20211122_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='doctor_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='patients',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='patients',
            name='patient_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
