# Generated by Django 3.2.6 on 2021-11-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedSightApp', '0018_auto_20211122_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='gender',
            field=models.CharField(default='gender', max_length=10),
        ),
        migrations.AlterField(
            model_name='patients',
            name='gender',
            field=models.CharField(default='gender', max_length=10),
        ),
    ]
